CREATE DATABASE agrodb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE agrodb;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  role ENUM('CLIENTE','PROFISSIONAL') NOT NULL DEFAULT 'CLIENTE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
